UPDATE ingredients SET "function" = 'Humectant' WHERE name = 'Butylene Glycol';
UPDATE ingredients SET "function" = 'Preservative' WHERE name = 'ISCAGUARD IAF';
UPDATE ingredients SET "function" = 'Active / Soothing' WHERE name = 'Panthenol';
UPDATE ingredients SET "function" = 'Thickener / Stabiliser' WHERE name = 'Pemulen TR1';
UPDATE ingredients SET "function" = 'Film-former' WHERE name = 'VP/VA Copolymer GC';
UPDATE ingredients SET "function" = 'Gum / Polymer' WHERE name = 'Solagum AX';
UPDATE ingredients SET "function" = 'Emulsifier' WHERE name = 'Olivem 1000';
UPDATE ingredients SET "function" = 'Preservative' WHERE name = 'Geogard ECT';
UPDATE ingredients SET "function" = 'Lipid' WHERE name = 'Capric/Caprylic Triglycerides';
UPDATE ingredients SET "function" = 'Emulsifier' WHERE name = 'Fluidifeel Easy (Seppic)';
UPDATE ingredients SET "function" = 'Emulsifier' WHERE name = 'Fluidifeel Easy';
UPDATE ingredients SET "function" = 'Emulsifier' WHERE name = 'Emulgade 1000 NI';
UPDATE ingredients SET "function" = 'Superfatting Agent' WHERE name = 'Peg-6 caprylic/capric glycerides';
UPDATE ingredients SET "function" = 'Lipid' WHERE name = 'Caprylic/capric triglycerides';
UPDATE ingredients SET "function" = 'Lipid' WHERE name = 'Sunflower oil (High Oleic)';
UPDATE ingredients SET "function" = 'Consistency Factor' WHERE name = 'Glyceryl stearate';
UPDATE ingredients SET "function" = 'Emulsifier' WHERE name = 'Polyglyceryl-4 Oleate';
UPDATE ingredients SET "function" = 'Active / Soothing' WHERE name = 'Allantoin';
UPDATE ingredients SET "function" = 'Active Phase-Shot' WHERE name = 'Caffeine';
UPDATE ingredients SET "function" = 'Active (Antioxidant)' WHERE name = 'Resveratrol 100% Pure Powder';
UPDATE ingredients SET "function" = 'Active (Antioxidant)' WHERE name = 'Green tea liposomes';
UPDATE ingredients SET "function" = 'Active / Soothing' WHERE name = 'Oat Protein Powder';
UPDATE ingredients SET "function" = 'Antioxidant' WHERE name = 'Tocopherol d-alpha 70%';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Salix alba (White Willow) Bark Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Urtica dioica (Nettle) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Betula alba (Birch) Bark Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Juniperus communis (Juniper) Berry Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Achillea millefolium (Yarrow) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Rosa damascena (Bulgarian Rose) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Melissa officinalis (Lemon Balm) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Vaccinium myrtillus (Bilberry) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Sambucus nigra (Elderflower) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Centaurea cyanus (Cornflower) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Tilia cordata (Linden Blossom) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Salvia officinalis (Sage) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hippophae rhamnoides (Sea Buckthorn) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Equisetum arvense (Horsetail) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Plantago major (Plantain) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hypericum perforatum (St. John''s Wort) Oil/Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hypericum perforatum (St. John''s Wort) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hippophae rhamnoides (Sea Buckthorn) Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hippophae rhamnoides (Sea Buckthorn) CO2 Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Betula alba (Birch) Sap Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Rosmarinus officinalis (Rosemary) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Rosmarinus officinalis (Rosemary) CO2 Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Sambucus nigra (Elderberry) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Vaccinium vitis-idaea (Lingonberry) Seed Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Ribes nigrum (Blackcurrant) Seed Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Vaccinium myrtillus (Bilberry) Seed Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Prunus spinosa (Blackthorn) Kernel Oil';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Arnica montana (Mountain Arnica) Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Centella asiatica GW';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Salix Nigra Bark Extract';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Urtica dioica Extract (Bulgaria)';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Vaccinium myrtillus Extract (EE)';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Achillea millefolium Extract (Carpathians)';
UPDATE ingredients SET "function" = 'EE Botanical Extract' WHERE name = 'Hippophae rhamnoides Extract (EE)';
UPDATE ingredients SET "function" = 'Lipid' WHERE name = 'Sweet Almond Oil';
UPDATE ingredients SET "function" = 'Lipid / Active' WHERE name = 'Oat oil';
UPDATE ingredients SET "function" = 'Lipid / Active' WHERE name = 'Cranberryöl cold pressed';

NOTIFY pgrst, 'reload schema';
