const fs = require("fs");

const API = "http://localhost:3000/api/recommend";

const TESTS = [
  {
    id: 1,
    name: "Young oily urban female - Breakouts focus",
    answers: {
      1: "25\u201334",
      2: "Female",
      3: "Central Europe (Germany, Poland, Czech Rep., Austria, Switzerland)",
      4: "Urban / City centre",
      5: 3,
      6: 4,
      7: 3,
      8: { "Vegetables & Fruits": 4, "Dairy": 3, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 3 },
      9: 2,
      10: "No",
      11: "Oily: shiny all over, especially T-zone",
      12: ["Breakouts or blemishes", "Oiliness or excess shine", "Enlarged pores"],
      13: 3,
      14: "Slightly oily: shine returns quickly",
      15: "Frequently, multiple times per month",
      16: ["None of the above"],
      17: 4,
      18: "Fair: sometimes burns, tans gradually",
      19: { "Hydration Level": 3, "Oiliness Level": 4, "Redness Level": 2, "Firmness / Elasticity": 4 },
      20: "No, never",
      21: "3\u20134 steps: cleanser, serum, moisturiser, SPF",
      22: "Lightweight gel: absorbs instantly, no residue",
      23: "Foaming / Gel cleanser: fresh, squeaky-clean feel",
      24: ["Clarifying (control oil, minimise breakouts)", "Brightening (even tone, radiance)", "Anti-aging (wrinkles, firmness, elasticity)", "Hydration (plump, dewy, moisturised)", "Calming (reduce redness, soothe irritation)", "Repair (strengthen barrier, heal damage)"],
      25: ["Science-first: proven clinical actives", "Clean beauty: no parabens, SLS, silicones"],
      26: 4,
      27: "Never, I\u2019m a retinol beginner",
      28: "2\u20135 minutes, quick but considered",
      29: ["Nothing specific, I\u2019m open to everything"],
      30: null,
    },
  },
  {
    id: 2,
    name: "Mature dry rural female - Anti-aging focus",
    answers: {
      1: "55\u201364",
      2: "Female",
      3: "Eastern Europe (Romania, Bulgaria, Ukraine, Russia)",
      4: "Rural / Countryside",
      5: 4,
      6: 3,
      7: 2,
      8: { "Vegetables & Fruits": 5, "Dairy": 2, "Sugar & Processed Foods": 1, "Omega-Rich Foods: Fish, Nuts, Seeds": 4 },
      9: 3,
      10: "No",
      11: "Dry: tight, flaky, sometimes rough",
      12: ["Fine lines or wrinkles", "Lack of firmness", "Dryness or dehydration"],
      13: 4,
      14: "Tight and dry: needs moisture immediately",
      15: "Rarely or never",
      16: ["None of the above"],
      17: 2,
      18: "Medium: rarely burns, tans well",
      19: { "Hydration Level": 2, "Oiliness Level": 1, "Redness Level": 2, "Firmness / Elasticity": 2 },
      20: "No, never",
      21: "3\u20134 steps: cleanser, serum, moisturiser, SPF",
      22: "Cream: rich and nourishing",
      23: "Cream / Milk cleanser: soft, non-stripping",
      24: ["Anti-aging (wrinkles, firmness, elasticity)", "Hydration (plump, dewy, moisturised)", "Repair (strengthen barrier, heal damage)", "Brightening (even tone, radiance)", "Calming (reduce redness, soothe irritation)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Natural / botanical-forward formulas", "Sustainably sourced ingredients"],
      26: 3,
      27: "Yes, occasionally. I use it a few times a month",
      28: "5\u201310 minutes, I enjoy the process",
      29: ["Nothing specific, I\u2019m open to everything"],
      30: null,
    },
  },
  {
    id: 3,
    name: "Young oily male - Anti-aging but NO retinol",
    answers: {
      1: "25\u201334",
      2: "Male",
      3: "North America",
      4: "Urban / City centre",
      5: 3,
      6: 3,
      7: 4,
      8: { "Vegetables & Fruits": 3, "Dairy": 3, "Sugar & Processed Foods": 3, "Omega-Rich Foods: Fish, Nuts, Seeds": 2 },
      9: 3,
      10: "No",
      11: "Oily: shiny all over, especially T-zone",
      12: ["Fine lines or wrinkles"],
      13: 2,
      14: "Slightly oily: shine returns quickly",
      15: "Occasionally, a few times per year",
      16: ["None of the above"],
      17: 3,
      18: "Dark: never burns",
      19: { "Hydration Level": 3, "Oiliness Level": 4, "Redness Level": 1, "Firmness / Elasticity": 3 },
      20: "No, never",
      21: "2 steps: cleanser + moisturiser",
      22: "Lightweight gel: absorbs instantly, no residue",
      23: "Foaming / Gel cleanser: fresh, squeaky-clean feel",
      24: ["Anti-aging (wrinkles, firmness, elasticity)", "Clarifying (control oil, minimise breakouts)", "Brightening (even tone, radiance)", "Hydration (plump, dewy, moisturised)", "Repair (strengthen barrier, heal damage)", "Calming (reduce redness, soothe irritation)"],
      25: ["Science-first: proven clinical actives"],
      26: 2,
      27: "Never, I\u2019m a retinol beginner",
      28: "Under 2 minutes, I want it fast",
      29: ["Retinol / retinoids"],
      30: null,
    },
  },
  {
    id: 4,
    name: "Pregnant oily female - Breakouts",
    answers: {
      1: "25\u201334",
      2: "Female",
      3: "Southern Europe (Mediterranean, Balkans)",
      4: "Suburban",
      5: 4,
      6: 3,
      7: 3,
      8: { "Vegetables & Fruits": 4, "Dairy": 3, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 3 },
      9: 2,
      10: "Yes",
      11: "Oily: shiny all over, especially T-zone",
      12: ["Breakouts or blemishes", "Oiliness or excess shine"],
      13: 3,
      14: "Slightly oily: shine returns quickly",
      15: "Monthly, often around my cycle",
      16: ["Hormonal acne (jawline, chin)"],
      17: 3,
      18: "Olive: almost never burns",
      19: { "Hydration Level": 3, "Oiliness Level": 4, "Redness Level": 2, "Firmness / Elasticity": 4 },
      20: "No, never",
      21: "2 steps: cleanser + moisturiser",
      22: "Lotion: light but hydrating",
      23: "Cream / Milk cleanser: soft, non-stripping",
      24: ["Clarifying (control oil, minimise breakouts)", "Calming (reduce redness, soothe irritation)", "Hydration (plump, dewy, moisturised)", "Anti-aging (wrinkles, firmness, elasticity)", "Brightening (even tone, radiance)", "Repair (strengthen barrier, heal damage)"],
      25: ["Clean beauty: no parabens, SLS, silicones", "Fragrance-free"],
      26: 1,
      27: "Never, I\u2019m a retinol beginner",
      28: "Under 2 minutes, I want it fast",
      29: ["Retinol / retinoids", "Exfoliating acids (AHA, BHA)"],
      30: null,
    },
  },
  {
    id: 5,
    name: "Dry skin + Rosacea - Calming focus",
    answers: {
      1: "35\u201344",
      2: "Female",
      3: "Northern Europe (Scandinavia, Baltics, UK, Ireland)",
      4: "Suburban",
      5: 3,
      6: 4,
      7: 3,
      8: { "Vegetables & Fruits": 4, "Dairy": 2, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 4 },
      9: 2,
      10: "No",
      11: "Dry: tight, flaky, sometimes rough",
      12: ["Redness or irritation", "Sensitivity or reactivity", "Dryness or dehydration"],
      13: 4,
      14: "Irritated or red: even water feels harsh",
      15: "Rarely or never",
      16: ["Rosacea or redness-prone skin"],
      17: 2,
      18: "Very fair: burns easily, rarely tans",
      19: { "Hydration Level": 2, "Oiliness Level": 1, "Redness Level": 5, "Firmness / Elasticity": 3 },
      20: "Yes, to fragrance or essential oils",
      21: "2 steps: cleanser + moisturiser",
      22: "Cream: rich and nourishing",
      23: "Cream / Milk cleanser: soft, non-stripping",
      24: ["Calming (reduce redness, soothe irritation)", "Hydration (plump, dewy, moisturised)", "Repair (strengthen barrier, heal damage)", "Anti-aging (wrinkles, firmness, elasticity)", "Brightening (even tone, radiance)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Fragrance-free", "Natural / botanical-forward formulas"],
      26: 1,
      27: "Never, I\u2019m a retinol beginner",
      28: "2\u20135 minutes, quick but considered",
      29: ["Fragrance / essential oils", "Exfoliating acids (AHA, BHA)"],
      30: "I have very reactive skin. My dermatologist told me to avoid fragrance.",
    },
  },
  {
    id: 6,
    name: "Dry skin + Eczema - Hydration focus",
    answers: {
      1: "35\u201344",
      2: "Female",
      3: "Central Europe (Germany, Poland, Czech Rep., Austria, Switzerland)",
      4: "Urban / City centre",
      5: 4,
      6: 3,
      7: 2,
      8: { "Vegetables & Fruits": 4, "Dairy": 1, "Sugar & Processed Foods": 1, "Omega-Rich Foods: Fish, Nuts, Seeds": 4 },
      9: 2,
      10: "No",
      11: "Dry: tight, flaky, sometimes rough",
      12: ["Dryness or dehydration", "Sensitivity or reactivity", "Texture irregularities"],
      13: 3,
      14: "Tight and dry: needs moisture immediately",
      15: "Rarely or never",
      16: ["Eczema or atopic dermatitis"],
      17: 1,
      18: "Fair: sometimes burns, tans gradually",
      19: { "Hydration Level": 1, "Oiliness Level": 1, "Redness Level": 3, "Firmness / Elasticity": 3 },
      20: "Yes, to fragrance or essential oils",
      21: "2 steps: cleanser + moisturiser",
      22: "Balm / Oil: very rich, cocooning",
      23: "Oil / Balm cleanser: dissolves everything, luxurious",
      24: ["Hydration (plump, dewy, moisturised)", "Repair (strengthen barrier, heal damage)", "Calming (reduce redness, soothe irritation)", "Anti-aging (wrinkles, firmness, elasticity)", "Brightening (even tone, radiance)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Fragrance-free", "Natural / botanical-forward formulas", "Vegan / cruelty-free"],
      26: 1,
      27: "Never, I\u2019m a retinol beginner",
      28: "2\u20135 minutes, quick but considered",
      29: ["Fragrance / essential oils"],
      30: null,
    },
  },
  {
    id: 7,
    name: "Combination skin - Brightening focus",
    answers: {
      1: "35\u201344",
      2: "Female",
      3: "Asia / Middle East",
      4: "Urban / City centre",
      5: 3,
      6: 3,
      7: 3,
      8: { "Vegetables & Fruits": 4, "Dairy": 2, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 4 },
      9: 4,
      10: "No",
      11: "Combination: oily T-zone, dry cheeks",
      12: ["Uneven skin tone or dark spots", "Dullness or tired-looking skin"],
      13: 3,
      14: "Comfortable: feels balanced",
      15: "Occasionally, a few times per year",
      16: ["Melasma or post-inflammatory hyperpigmentation"],
      17: 2,
      18: "Medium: rarely burns, tans well",
      19: { "Hydration Level": 3, "Oiliness Level": 3, "Redness Level": 2, "Firmness / Elasticity": 3 },
      20: "No, never",
      21: "3\u20134 steps: cleanser, serum, moisturiser, SPF",
      22: "Lotion: light but hydrating",
      23: "Micellar / Lotion: gentle, no-rinse",
      24: ["Brightening (even tone, radiance)", "Anti-aging (wrinkles, firmness, elasticity)", "Hydration (plump, dewy, moisturised)", "Calming (reduce redness, soothe irritation)", "Repair (strengthen barrier, heal damage)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Science-first: proven clinical actives"],
      26: 4,
      27: "Tried once or twice, didn\u2019t stick with it",
      28: "5\u201310 minutes, I enjoy the process",
      29: ["Nothing specific, I\u2019m open to everything"],
      30: null,
    },
  },
  {
    id: 8,
    name: "Sensitive skin - Calming focus",
    answers: {
      1: "25\u201334",
      2: "Female",
      3: "Northern Europe (Scandinavia, Baltics, UK, Ireland)",
      4: "Suburban",
      5: 4,
      6: 4,
      7: 2,
      8: { "Vegetables & Fruits": 5, "Dairy": 1, "Sugar & Processed Foods": 1, "Omega-Rich Foods: Fish, Nuts, Seeds": 5 },
      9: 1,
      10: "No",
      11: "Sensitive: easily irritated, reactive to new products",
      12: ["Redness or irritation", "Sensitivity or reactivity"],
      13: 5,
      14: "Irritated or red: even water feels harsh",
      15: "Rarely or never",
      16: ["Contact allergies to cosmetic ingredients"],
      17: 1,
      18: "Very fair: burns easily, rarely tans",
      19: { "Hydration Level": 3, "Oiliness Level": 1, "Redness Level": 4, "Firmness / Elasticity": 4 },
      20: "I have multiple known sensitivities",
      21: "1 step: I just wash my face",
      22: "Cream: rich and nourishing",
      23: "Cream / Milk cleanser: soft, non-stripping",
      24: ["Calming (reduce redness, soothe irritation)", "Hydration (plump, dewy, moisturised)", "Repair (strengthen barrier, heal damage)", "Brightening (even tone, radiance)", "Anti-aging (wrinkles, firmness, elasticity)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Fragrance-free", "Clean beauty: no parabens, SLS, silicones", "Natural / botanical-forward formulas"],
      26: 1,
      27: "Never, I\u2019m a retinol beginner",
      28: "Under 2 minutes, I want it fast",
      29: ["Fragrance / essential oils", "Retinol / retinoids", "Exfoliating acids (AHA, BHA)"],
      30: "Very sensitive skin, react to almost everything.",
    },
  },
  {
    id: 9,
    name: "Oily male - Excludes BHA + PEGs",
    answers: {
      1: "25\u201334",
      2: "Male",
      3: "Central Europe (Germany, Poland, Czech Rep., Austria, Switzerland)",
      4: "Urban / City centre",
      5: 3,
      6: 3,
      7: 4,
      8: { "Vegetables & Fruits": 3, "Dairy": 3, "Sugar & Processed Foods": 4, "Omega-Rich Foods: Fish, Nuts, Seeds": 2 },
      9: 2,
      10: "No",
      11: "Oily: shiny all over, especially T-zone",
      12: ["Breakouts or blemishes", "Enlarged pores", "Oiliness or excess shine"],
      13: 2,
      14: "Slightly oily: shine returns quickly",
      15: "Frequently, multiple times per month",
      16: ["None of the above"],
      17: 4,
      18: "Dark: never burns",
      19: { "Hydration Level": 3, "Oiliness Level": 5, "Redness Level": 1, "Firmness / Elasticity": 4 },
      20: "No, never",
      21: "1 step: I just wash my face",
      22: "Lightweight gel: absorbs instantly, no residue",
      23: "Foaming / Gel cleanser: fresh, squeaky-clean feel",
      24: ["Clarifying (control oil, minimise breakouts)", "Brightening (even tone, radiance)", "Anti-aging (wrinkles, firmness, elasticity)", "Hydration (plump, dewy, moisturised)", "Calming (reduce redness, soothe irritation)", "Repair (strengthen barrier, heal damage)"],
      25: ["Science-first: proven clinical actives"],
      26: 4,
      27: "Never, I\u2019m a retinol beginner",
      28: "Under 2 minutes, I want it fast",
      29: ["Exfoliating acids (AHA, BHA)", "PEGs"],
      30: null,
    },
  },
  {
    id: 10,
    name: "Dry female - Multiple concerns, Repair #1",
    answers: {
      1: "45\u201354",
      2: "Female",
      3: "Eastern Europe (Romania, Bulgaria, Ukraine, Russia)",
      4: "Rural / Countryside",
      5: 3,
      6: 3,
      7: 3,
      8: { "Vegetables & Fruits": 4, "Dairy": 2, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 3 },
      9: 3,
      10: "No",
      11: "Dry: tight, flaky, sometimes rough",
      12: ["Texture irregularities", "Dryness or dehydration", "Sensitivity or reactivity"],
      13: 3,
      14: "Tight and dry: needs moisture immediately",
      15: "Rarely or never",
      16: ["None of the above"],
      17: 2,
      18: "Medium: rarely burns, tans well",
      19: { "Hydration Level": 2, "Oiliness Level": 1, "Redness Level": 2, "Firmness / Elasticity": 3 },
      20: "No, never",
      21: "3\u20134 steps: cleanser, serum, moisturiser, SPF",
      22: "Cream: rich and nourishing",
      23: "Oil / Balm cleanser: dissolves everything, luxurious",
      24: ["Repair (strengthen barrier, heal damage)", "Hydration (plump, dewy, moisturised)", "Calming (reduce redness, soothe irritation)", "Anti-aging (wrinkles, firmness, elasticity)", "Brightening (even tone, radiance)", "Clarifying (control oil, minimise breakouts)"],
      25: ["Natural / botanical-forward formulas", "Sustainably sourced ingredients"],
      26: 3,
      27: "Tried once or twice, didn\u2019t stick with it",
      28: "5\u201310 minutes, I enjoy the process",
      29: ["Nothing specific, I\u2019m open to everything"],
      30: null,
    },
  },
  {
    id: 11,
    name: "Oily + Eczema (gap test)",
    answers: {
      1: "25\u201334",
      2: "Female",
      3: "Central Europe (Germany, Poland, Czech Rep., Austria, Switzerland)",
      4: "Urban / City centre",
      5: 3,
      6: 3,
      7: 3,
      8: { "Vegetables & Fruits": 3, "Dairy": 2, "Sugar & Processed Foods": 2, "Omega-Rich Foods: Fish, Nuts, Seeds": 3 },
      9: 2,
      10: "No",
      11: "Oily: shiny all over, especially T-zone",
      12: ["Breakouts or blemishes"],
      13: 3,
      14: "Slightly oily: shine returns quickly",
      15: "Frequently, multiple times per month",
      16: ["Eczema or atopic dermatitis"],
      17: 3,
      18: "Fair: sometimes burns, tans gradually",
      19: { "Hydration Level": 3, "Oiliness Level": 4, "Redness Level": 3, "Firmness / Elasticity": 4 },
      20: "Yes, to fragrance or essential oils",
      21: "2 steps: cleanser + moisturiser",
      22: "Lightweight gel: absorbs instantly, no residue",
      23: "Foaming / Gel cleanser: fresh, squeaky-clean feel",
      24: ["Clarifying (control oil, minimise breakouts)", "Calming (reduce redness, soothe irritation)", "Hydration (plump, dewy, moisturised)", "Anti-aging (wrinkles, firmness, elasticity)", "Brightening (even tone, radiance)", "Repair (strengthen barrier, heal damage)"],
      25: ["Fragrance-free", "Clean beauty: no parabens, SLS, silicones"],
      26: 1,
      27: "Never, I\u2019m a retinol beginner",
      28: "Under 2 minutes, I want it fast",
      29: ["Fragrance / essential oils"],
      30: null,
    },
  },
];

async function runTests() {
  const results = [];

  for (const test of TESTS) {
    const r = await fetch(API, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ answers: test.answers }),
    });
    const d = await r.json();

    const result = {
      testId: test.id,
      testName: test.name,
      skinType: d.skinType,
      concerns: d.concerns,
      hasGap: d.hasGap,
      gapMessage: d.gapMessage || null,
      winner: d.serum ? d.serum.product.name : "GAP",
      score: d.serum ? d.serum.score : 0,
      matchedConcerns: d.serum ? d.serum.matchedConcerns : [],
      reasons: d.serum ? d.serum.reasons : [],
      usedConcernTags: d.serum ? (d.serum.product.concern_tags && d.serum.product.concern_tags.length > 0) : false,
      safetyFlags: d.serum ? {
        safe_for_pregnancy: d.serum.product.safe_for_pregnancy,
        safe_for_rosacea: d.serum.product.safe_for_rosacea,
        safe_for_eczema: d.serum.product.safe_for_eczema,
        contains_retinol: d.serum.product.contains_retinol,
        contains_bha: d.serum.product.contains_bha,
        contains_pegs: d.serum.product.contains_pegs,
        contains_fragrance: d.serum.product.contains_fragrance,
      } : null,
      quizAnswers: test.answers,
    };

    results.push(result);

    console.log("=== TEST " + test.id + ": " + test.name + " ===");
    console.log("Skin:", d.skinType, "| Concerns:", JSON.stringify(d.concerns));
    if (d.serum) {
      console.log("Winner:", d.serum.product.name, "| Score:", d.serum.score);
      console.log("Source:", result.usedConcernTags ? "CONCERN TAGS" : "LAYER 2");
      console.log("Matched:", JSON.stringify(d.serum.matchedConcerns));
      console.log("Reasons:", JSON.stringify(d.serum.reasons));
      console.log("Safety:", JSON.stringify(result.safetyFlags));
    } else {
      console.log("GAP:", d.gapMessage);
    }
    console.log("");
  }

  fs.writeFileSync(
    "C:/Users/Egofoxxx/Documents/Development Area/Web Development Kyrill/docs/test-results-raw.json",
    JSON.stringify(results, null, 2)
  );
  console.log("Raw results saved to docs/test-results-raw.json");
}

runTests().catch(console.error);
