-- Skincare priorities mapping
-- Generated from Kyrill Excel
-- 69 ingredients mapped

UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Rosmarinus officinalis (Rosemary) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Sambucus nigra (Elderberry) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Vaccinium myrtillus (Bilberry) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Hippophae rhamnoides (Sea Buckthorn) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Melissa officinalis (Lemon Balm) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair','Clarifying']::text[] WHERE LOWER(name) = LOWER('Achillea millefolium (Yarrow) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair','Hydration']::text[] WHERE LOWER(name) = LOWER('Plantago major (Plantain) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Hydration']::text[] WHERE LOWER(name) = LOWER('Tilia cordata (Linden Blossom) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair','Hydration']::text[] WHERE LOWER(name) = LOWER('Calendula officinalis (Marigold) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming']::text[] WHERE LOWER(name) = LOWER('Matricaria chamomilla (Chamomile) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying','Calming']::text[] WHERE LOWER(name) = LOWER('Urtica dioica (Nettle) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying']::text[] WHERE LOWER(name) = LOWER('Juniperus communis (Juniper) Berry Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Betula alba (Birch) Bark Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Hydration']::text[] WHERE LOWER(name) = LOWER('Sambucus nigra (Elderflower) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Equisetum arvense (Horsetail) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying','Repair']::text[] WHERE LOWER(name) = LOWER('Salix alba (White Willow) Bark Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Hydration','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Rosa damascena (Bulgarian Rose) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Calming','Hydration']::text[] WHERE LOWER(name) = LOWER('Centaurea cyanus (Cornflower) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying']::text[] WHERE LOWER(name) = LOWER('Salvia officinalis (Sage) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging','Brightening','Repair']::text[] WHERE LOWER(name) = LOWER('Rosa canina (Rosehip) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration','Brightening']::text[] WHERE LOWER(name) = LOWER('Betula alba (Birch) Sap Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Hypericum perforatum (St. John''s Wort) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration','Anti-aging','Calming']::text[] WHERE LOWER(name) = LOWER('Hippophae rhamnoides (Sea Buckthorn) Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging','Brightening','Repair']::text[] WHERE LOWER(name) = LOWER('Rosa canina (Rosehip) Seed Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration','Brightening','Calming']::text[] WHERE LOWER(name) = LOWER('Vaccinium vitis-idaea (Lingonberry) Seed Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration','Calming','Brightening']::text[] WHERE LOWER(name) = LOWER('Ribes nigrum (Blackcurrant) Seed Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration','Anti-aging','Brightening']::text[] WHERE LOWER(name) = LOWER('Prunus spinosa (Blackthorn) Kernel Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Rosmarinus officinalis (Rosemary) CO2 Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging','Hydration']::text[] WHERE LOWER(name) = LOWER('Hippophae rhamnoides (Sea Buckthorn) CO2 Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Vaccinium myrtillus (Bilberry) Seed Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Hypericum perforatum (St. John''s Wort) Oil/Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Hydration','Repair']::text[] WHERE LOWER(name) = LOWER('Calendula officinalis (Marigold) CO2/Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming']::text[] WHERE LOWER(name) = LOWER('Matricaria chamomilla (Chamomile) CO2 Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging','Brightening','Repair']::text[] WHERE LOWER(name) = LOWER('Rosa canina (Rosehip) Extract/Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging','Clarifying']::text[] WHERE LOWER(name) = LOWER('Betula alba (Birch) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Calendula officinalis (Marigold) CO2 Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Brightening']::text[] WHERE LOWER(name) = LOWER('Arnica montana (Mountain Arnica) Extract');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming']::text[] WHERE LOWER(name) = LOWER('Oat Oil');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Cranberryöl cold pressed');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying']::text[] WHERE LOWER(name) = LOWER('Salicylic Acid');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Clarifying']::text[] WHERE LOWER(name) = LOWER('Niacinamide');
UPDATE ingredients SET skincare_priorities = ARRAY['Clarifying']::text[] WHERE LOWER(name) = LOWER('Zinc PCA');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Tranexamic Acid');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Azeloglycine');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration']::text[] WHERE LOWER(name) = LOWER('DPG (Dipropylene Glycol)');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Matrixyl 3000 (Anti-aging dipeptide)');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Retinol Liposome OS');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Retinol in Phytosqualane');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('SymRenew HPR');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging','Calming']::text[] WHERE LOWER(name) = LOWER('Bakuchiol');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Hydration','Repair']::text[] WHERE LOWER(name) = LOWER('Panthenol');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Allantoin');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming']::text[] WHERE LOWER(name) = LOWER('Bisabolol');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming']::text[] WHERE LOWER(name) = LOWER('Ectoin');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair','Hydration']::text[] WHERE LOWER(name) = LOWER('Ceramide-Complex');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration']::text[] WHERE LOWER(name) = LOWER('4D MB Hyaluronic Acid');
UPDATE ingredients SET skincare_priorities = ARRAY['Hydration']::text[] WHERE LOWER(name) = LOWER('Aquaxyl');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Betaglucano sol.');
UPDATE ingredients SET skincare_priorities = ARRAY['Repair','Brightening']::text[] WHERE LOWER(name) = LOWER('Gluconolactone');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Repair']::text[] WHERE LOWER(name) = LOWER('Oat Protein Powder');
UPDATE ingredients SET skincare_priorities = ARRAY['Anti-aging']::text[] WHERE LOWER(name) = LOWER('Sepilift DPHP');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Stabilized Coenzyme Q10 (Liquid)');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Vitamin C - Ascorbyl Tetraisopalmitate');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Resveratrol 100% Pure Powder');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Calming']::text[] WHERE LOWER(name) = LOWER('Green Tea Liposomes');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Vitamin E plant-based');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening']::text[] WHERE LOWER(name) = LOWER('Tocopherol d-alpha 70%');
UPDATE ingredients SET skincare_priorities = ARRAY['Brightening','Anti-aging']::text[] WHERE LOWER(name) = LOWER('Cosphaderm Tocopharin');
UPDATE ingredients SET skincare_priorities = ARRAY['Calming','Brightening']::text[] WHERE LOWER(name) = LOWER('Organic Green Tea Extract');

NOTIFY pgrst, 'reload schema';
